version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - pip install -r requirements.txt
  post_build:
    commands:
      - python lambda_function.py
artifacts:
  files: lambda_function.py
